DELETE FROM F1_DATA.PUBLIC.CONSTRUCTORS WHERE C1 = 'constructorId';

ALTER TABLE F1_DATA.PUBLIC.CONSTRUCTORS RENAME COLUMN C1 TO CONSTRUCTORID;
ALTER TABLE F1_DATA.PUBLIC.CONSTRUCTORS RENAME COLUMN C2 TO CONSTRUCTORREF;
ALTER TABLE F1_DATA.PUBLIC.CONSTRUCTORS RENAME COLUMN C3 TO CON_NAME;
ALTER TABLE F1_DATA.PUBLIC.CONSTRUCTORS RENAME COLUMN C4 TO NATIONALITY;
ALTER TABLE F1_DATA.PUBLIC.CONSTRUCTORS RENAME COLUMN C5 TO REF_URL;



DELETE FROM F1_DATA.PUBLIC.DRIVERS WHERE C1 = 'driverId';

ALTER TABLE F1_DATA.PUBLIC.DRIVERS RENAME COLUMN C1 TO DRIVERID;
ALTER TABLE F1_DATA.PUBLIC.DRIVERS RENAME COLUMN C2 TO DRIVERREF;
ALTER TABLE F1_DATA.PUBLIC.DRIVERS RENAME COLUMN C3 TO DRIVER_NUMBER;
ALTER TABLE F1_DATA.PUBLIC.DRIVERS RENAME COLUMN C4 TO DRIVER_CODE;
ALTER TABLE F1_DATA.PUBLIC.DRIVERS RENAME COLUMN C5 TO DRIVER_FORENAME;
ALTER TABLE F1_DATA.PUBLIC.DRIVERS RENAME COLUMN C6 TO DRIVER_SURNAME;
ALTER TABLE F1_DATA.PUBLIC.DRIVERS RENAME COLUMN C7 TO DRIVER_DOB;
ALTER TABLE F1_DATA.PUBLIC.DRIVERS RENAME COLUMN C8 TO DRIVER_NAT;
ALTER TABLE F1_DATA.PUBLIC.DRIVERS RENAME COLUMN C9 TO DRIVER_REF_URL;
