
CREATE OR REPLACE TABLE F1_DATA.PUBLIC.GLOBAL_CONSTRUCTOR_STANDINGS AS


WITH CON_DATA_CLEAN AS (
    SELECT
        TRY_CAST(CONSTRUCTORID AS NUMBER) AS CONSTRUCTOR_ID,
        CON_NAME                          AS BRAND_NAME
    FROM F1_DATA.PUBLIC.CONSTRUCTORS
    WHERE TRY_CAST(CONSTRUCTORID AS NUMBER) IS NOT NULL
)

SELECT
    -- Constructor identity
    c.CONSTRUCTOR_ID,
    c.BRAND_NAME,

    -- CONSTRUCTOR_RESULTS table
    cr.RACEID               AS RACE_ID,
    cr.POINTS               AS CONSTRUCTOR_POINTS,

    -- CONSTRUCTOR_STANDINGS table
    cs.POINTS               AS CON_STANDING_POINTS,
    cs.POSITION             AS CONSTRUCTOR_POSITION,
    cs.WINS                 AS CONSTRUCTOR_WINS

FROM CON_DATA_CLEAN c

-- Join CONSTRUCTOR_RESULTS on CONSTRUCTOR_ID
JOIN F1_DATA.PUBLIC.CONSTRUCTOR_RESULTS cr
    ON c.CONSTRUCTOR_ID = cr.CONSTRUCTORID

-- Join CONSTRUCTOR_STANDINGS on both CONSTRUCTOR_ID and RACE_ID
LEFT JOIN F1_DATA.PUBLIC.CONSTRUCTOR_STANDINGS cs
    ON c.CONSTRUCTOR_ID = cs.CONSTRUCTORID
    AND cr.RACEID = cs.RACEID;
